version: '3'
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.4.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'db.jzwgtsbaaznxyqpfxpwe.supabase.co'
      DB_PORT: '5432'
      DB_DATABASE: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'NpJTv0Eq&Ao5xaLU'
      DB_SSL: 'false'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'ryan@cooperonlineenterprises.com'
      ADMIN_PASSWORD: '@JRC-vkc-1975@'

      RATE_LIMITER_ENABLED: 'false'
      RATE_LIMITER_STORE: 'memory'
      RATE_LIMITER_POINTS: '25'
      RATE_LIMITER_DURATION: '1'

      ASSETS_CACHE_TTL: '30d'

      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_DRIVER: 'local'
      STORAGE_LOCAL_ROOT: './uploads'

      ACCESS_TOKEN_TTL: '15m'
      REFRESH_TOKEN_TTL: '7d'
      REFRESH_TOKEN_COOKIE_SECURE: 'false'
      REFRESH_TOKEN_COOKIE_SAME_SITE: 'lax'
      REFRESH_TOKEN_COOKIE_NAME: 'directus_refresh_token'

      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      CORS_CREDENTIALS: 'true'
      CORS_MAX_AGE: '18000'

      EXTENSIONS_PATH: './extensions'
      EXTENSIONS_AUTO_RELOAD: 'false'

      EMAIL_FROM: 'no-reply@directus.io'
      EMAIL_TRANSPORT: 'sendmail'
      EMAIL_SENDMAIL_NEW_LINE: 'unix'
      EMAIL_SENDMAIL_PATH: '/usr/sbin/sendmail'

      PUBLIC_URL: 'https://wrote.render.com'

      
      
